CRUD Posts
DaniloDO/multitaskr-blog-api pull request #5
Opened 2022-11-11 01:34 UTC by DaniloDO

2022-11-11 01:35 UTC, williardxzd requested changes

2022-11-11 01:35 UTC, williardxzd commented on app/Http/Controllers/PostController.php
> +<?php
Te faltaron las funciones en el controlador, los resources y los request

2022-11-15 00:14 UTC, williardxzd requested changes

2022-11-15 00:14 UTC, williardxzd commented on app/Http/Requests/PostsRequest.php
> +            'published_at' => 'nullable',
No puedes guardar el published_at enviando `01-01-01` es una fecha incorrecta para un datetime. Tienes que mandarla como `2022-10-30 00:00:00` y aqui en este file lo validas como: `Y-m-d H:i:s`.

Te recomiendo checarte los tipos de formatos de fechas para PHP: https://www.php.net/manual/en/datetime.format.php

Son distintos a los de Javascript, por ejemplo `YYYY` es `Y` en PHP, y asi con lo demas...

2022-11-15 18:16 UTC, DaniloDO commented on app/Http/Controllers/PostController.php
> +<?php
Ya incluido el controlador, resources y requests

2022-11-15 18:18 UTC, DaniloDO commented on app/Http/Requests/PostsRequest.php
> +            'published_at' => 'nullable',
Solventado el problema sobre el formato de la fecha al usar el PostFactory

2022-11-15 23:44 UTC, merged